repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        additional_dependencies: [
          httpx>=0.25.0,
          pydantic>=2.0.0,
          rich>=13.0.0,
          python-dotenv>=1.0.0,
          pytest>=7.0.0,
          pytest-asyncio>=0.21.0,
          nox,
          "."
        ]
