name: 'Setup Python Environment'
description: 'Set up Python, uv, and install dependencies'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    - name: Install dependencies
      run: uv sync --extra dev
      shell: bash
