name: Python Code Quality

on:
  pull_request:
    branches: [ main ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python Environment
      uses: ./.github/actions/setup-python-env
    - name: Run Ruff (format check)
      run: uv run ruff format --check --diff src/ tests/

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python Environment
      uses: ./.github/actions/setup-python-env
    - name: Run Ruff (linting)
      run: uv run ruff check src/ tests/

  type-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python Environment
      uses: ./.github/actions/setup-python-env
    - name: Run MyPy (type checking)
      run: uv run mypy src/

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python Environment
      uses: ./.github/actions/setup-python-env
    - name: Run tests
      run: uv run pytest

